- name:  first play
  hosts:  all
  tasks:
    - name: create a new file
      file:
        path:  /tmp/foo2.conf
        mode:  0664
        owner:  bhargav
        state:  touch
    - name:  install tmux
      package:
        name: tmux
        state:  present
